
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPService", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPService {


    /**
     * 
     * @param string
     * @return
     *     returns web.GroupTransaction
     */
    @WebMethod
    @WebResult(name = "GroupOfUsers", partName = "GroupOfUsers")
    @Action(input = "http://web/SOAPService/readAllByUsernameRequest", output = "http://web/SOAPService/readAllByUsernameResponse")
    public GroupTransaction readAllByUsername(
        @WebParam(name = "String", partName = "String")
        String string);

    /**
     * 
     * @param name
     * @return
     *     returns web.User
     */
    @WebMethod
    @WebResult(name = "Username", partName = "Username")
    @Action(input = "http://web/SOAPService/readByUsernameRequest", output = "http://web/SOAPService/readByUsernameResponse")
    public User readByUsername(
        @WebParam(name = "name", partName = "name")
        String name);

    /**
     * 
     * @param username
     */
    @WebMethod
    @Action(input = "http://web/SOAPService/createAccountRequest", output = "http://web/SOAPService/createAccountResponse")
    public void createAccount(
        @WebParam(name = "Username", partName = "Username")
        User username);

}
