
package org.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://employee.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @return
     *     returns org.employee.GroupOfEmployee
     */
    @WebMethod
    @WebResult(name = "findAll", partName = "findAll")
    @Action(input = "http://employee.org/EmployeeService/getAllEmployeeRequest", output = "http://employee.org/EmployeeService/getAllEmployeeResponse")
    public GroupOfEmployee getAllEmployee();

    /**
     * 
     * @param pincode
     * @return
     *     returns org.employee.GroupOfEmployee
     */
    @WebMethod
    @WebResult(name = "ListPincode", partName = "ListPincode")
    @Action(input = "http://employee.org/EmployeeService/searchByPincodeRequest", output = "http://employee.org/EmployeeService/searchByPincodeResponse")
    public GroupOfEmployee searchByPincode(
        @WebParam(name = "pincode", partName = "pincode")
        int pincode);

    /**
     * 
     * @param employee
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://employee.org/EmployeeService/createEmployeeRequest", output = "http://employee.org/EmployeeService/createEmployeeResponse")
    public String createEmployee(
        @WebParam(name = "Employee", partName = "Employee")
        EmployeePersonalDetails employee);

}
