//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.29 at 02:07:03 PM IST 
//


package services.transaction;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the services.transaction package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: services.transaction
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindBySenderRequest }
     * 
     */
    public FindBySenderRequest createFindBySenderRequest() {
        return new FindBySenderRequest();
    }

    /**
     * Create an instance of {@link FindByReceiveResponse }
     * 
     */
    public FindByReceiveResponse createFindByReceiveResponse() {
        return new FindByReceiveResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link RemoveResponse }
     * 
     */
    public RemoveResponse createRemoveResponse() {
        return new RemoveResponse();
    }

    /**
     * Create an instance of {@link NewTransactionRequest }
     * 
     */
    public NewTransactionRequest createNewTransactionRequest() {
        return new NewTransactionRequest();
    }

    /**
     * Create an instance of {@link RemoveRequest }
     * 
     */
    public RemoveRequest createRemoveRequest() {
        return new RemoveRequest();
    }

    /**
     * Create an instance of {@link UpdateRemarkResponse }
     * 
     */
    public UpdateRemarkResponse createUpdateRemarkResponse() {
        return new UpdateRemarkResponse();
    }

    /**
     * Create an instance of {@link FindByReceiveRequest }
     * 
     */
    public FindByReceiveRequest createFindByReceiveRequest() {
        return new FindByReceiveRequest();
    }

    /**
     * Create an instance of {@link FindBySenderResponse }
     * 
     */
    public FindBySenderResponse createFindBySenderResponse() {
        return new FindBySenderResponse();
    }

    /**
     * Create an instance of {@link FindByAmountRequest }
     * 
     */
    public FindByAmountRequest createFindByAmountRequest() {
        return new FindByAmountRequest();
    }

    /**
     * Create an instance of {@link NewTransactionResponse }
     * 
     */
    public NewTransactionResponse createNewTransactionResponse() {
        return new NewTransactionResponse();
    }

    /**
     * Create an instance of {@link FindByAmountResponse }
     * 
     */
    public FindByAmountResponse createFindByAmountResponse() {
        return new FindByAmountResponse();
    }

    /**
     * Create an instance of {@link UpdateRemarksRequest }
     * 
     */
    public UpdateRemarksRequest createUpdateRemarksRequest() {
        return new UpdateRemarksRequest();
    }

}
